name: CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

env:
  DOCKER_USERNAME: jrevillard

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/edulift-backend:latest
          platforms: linux/amd64,linux/arm64
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/edulift-frontend:latest
          platforms: linux/amd64,linux/arm64

  deploy-info:
    name: Deployment Info
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
      - name: Create deployment summary
        run: |
          echo "Docker images pushed to Docker Hub:" >> $GITHUB_STEP_SUMMARY
          echo "- Backend: ${{ env.DOCKER_USERNAME }}/edulift-backend:latest" >> $GITHUB_STEP_SUMMARY
          echo "- Frontend: ${{ env.DOCKER_USERNAME }}/edulift-frontend:latest" >> $GITHUB_STEP_SUMMARY